import React, { Component } from 'react'
import { Popper, Paper } from '@material-ui/core'
import {EditorView} from "prosemirror-view"
import EditorGutter from "./EditorGutter"
// import applyDevTools from "prosemirror-dev-tools";
import {undo, redo} from "prosemirror-history"

import ProseMirrorComponent from "../../common/ProseMirrorComponent"
import {transformPastedHTMLHandler,transformPastedHandler, createClipboardSerializer, cutSelectedNode, copySelectedNode, pasteSelectedNode} from "../../../model/cut-and-paste"
import {addTextNodes} from "../../../model/xml"

export default class NotePopup extends Component {

    constructor() {
        super()
        this.state = {
            currentNoteID: null
        }
    }

    createEditorView = (element) => {
        const { teiDocument, noteID } = this.props
        const { teiSchema } = teiDocument.fairCopyProject
        const { noteEditorView } = teiDocument

        if( !noteID ) {
            this.saveSubDoc()
            this.setState({...this.state, noteEditorView: null})
            return
        } 

        if( noteEditorView ) return
        const initialState = teiDocument.openSubDocument( noteID )
        this.clipboardSerializer = createClipboardSerializer(teiSchema,teiDocument)

        const editorView = new EditorView( 
            element,
            { 
                dispatchTransaction: this.dispatchTransaction,
                state: initialState,
                transformPastedHTML: transformPastedHTMLHandler(teiSchema),
                transformPasted: transformPastedHandler(teiSchema),
                clipboardSerializer: this.clipboardSerializer
            }
        )
        // if( process.env['NODE_ENV'] === 'development' ) applyDevTools(editorView)
        editorView.focus()
        teiDocument.noteEditorView = editorView
        addTextNodes(editorView.state,editorView.dispatch)

        this.setState( { ...this.state, currentNoteID: noteID } )
    }

    dispatchTransaction = (transaction) => {
        const { teiDocument, onStateChange, onAlertMessage, onChangePos } = this.props
        const { noteEditorView } = teiDocument

        // TODO how to handle error counts here?

        // display error messages generated by this transaction
        const alertMessage = transaction.getMeta('alertMessage')
        if( alertMessage ) {
            onAlertMessage(alertMessage)
        }

        let editorGutterPos = transaction.getMeta('editorGutterPos')
        const editorGutterPath = transaction.getMeta('editorGutterPath')
        if( editorGutterPos !== undefined ) {
            onChangePos(editorGutterPos, editorGutterPath)
            onStateChange(editorGutterPos)
        } else {
            editorGutterPos = this.props.editorGutterPos
        }

        if( noteEditorView ) {
            const editorState = noteEditorView.state
            const nextEditorState = editorState.apply(transaction)
            noteEditorView.updateState(nextEditorState)
            teiDocument.changedSinceLastSave = teiDocument.changedSinceLastSave || transaction.docChanged
        }
    }

    saveSubDoc() {
        const { teiDocument } = this.props
        const { noteEditorView } = teiDocument
        const { currentNoteID } = this.state
        if( noteEditorView ) {
            const editorState = noteEditorView.state
            teiDocument.saveSubDoc(currentNoteID,editorState)                
        }
    }

    destroyEditorView = (editorView) => {
        const { teiDocument } = this.props
        this.saveSubDoc()
        editorView.destroy()
        teiDocument.noteEditorView = null
        this.setState({ ...this.state, currentNoteID: null })
    }

    onChangePos = (editorGutterPos, editorGutterPath) => {
        const { teiDocument } = this.props 
        const editorView = teiDocument.getActiveView()
        const { tr } = editorView.state
        tr.setMeta( 'editorGutterPos', editorGutterPos )
        tr.setMeta( 'editorGutterPath', editorGutterPath )
        tr.setMeta( 'highlightEnabled', editorGutterPos === null )
        editorView.dispatch(tr)
    }

    onKeyDown = ( event ) => {
        const { teiDocument } = this.props
        const editorView = teiDocument.getActiveView()
        const metaKey = ( event.ctrlKey || event.metaKey )

        const key = event.key.toLowerCase()

        // TODO support Escape for closing and saving

        if( metaKey && key === 'x' ) {
            cutSelectedNode( teiDocument, this.clipboardSerializer )
        }

        if( metaKey && key === 'c' ) {
            copySelectedNode( teiDocument, this.clipboardSerializer )
        }

        if( metaKey && key === 'v' ) {
            pasteSelectedNode( teiDocument )
        }

        if( metaKey && key === 'z' ) {
            undo(editorView.state,editorView.dispatch)
        } 
        if( metaKey && ((event.shiftKey && key === 'z') || key === 'y' )) {
            redo(editorView.state,editorView.dispatch)
        } 
    }

    renderEditor() {
        const { teiDocument, expanded, editorGutterPos, editorGutterPath, onDragElement } = this.props
        const { noteEditorView } = teiDocument

        const onRef = (el) => {
            this.el = el
        }

        const gutterTop = (this.el) ? this.el.getBoundingClientRect().top - 5 : 0
        // if( this.el ) console.log(`top: ${gutterTop}`)

        return (
            <div className='note-body' ref={onRef} onKeyDown={this.onKeyDown} >
                <EditorGutter 
                    gutterTop={gutterTop}
                    expanded={expanded}
                    onDragElement={onDragElement}
                    teiDocument={teiDocument}
                    editorView={noteEditorView}
                    editorGutterPath={editorGutterPath}
                    editorGutterPos={editorGutterPos}
                    onChangePos={this.onChangePos}
                /> 
                <ProseMirrorComponent
                    destroyEditorView={this.destroyEditorView}
                    createEditorView={this.createEditorView}
                    editorView={noteEditorView}
                />                  
            </div>
        )        
    }

    render() {
        const { anchorEl } = this.props

        if( !anchorEl ) return null

        const placement = 'bottom-start'
        const elevation = 6

        return (
            <div id="NotePopup">
                 <Popper className="note-popup" placement={placement} open={true} anchorEl={anchorEl} role={undefined} disablePortal>
                    <Paper elevation={elevation}>
                        { this.renderEditor() }            
                    </Paper>
                </Popper>
            </div>
        )
    }
}
